package com.p2pnexus.comun;

public enum TipoMensaje {

    NOTIFICACION,

    // Mensajes de consulta
    S_TEST,
    S_LOGIN,
    S_REGISTRO,
    S_SOLICITAR_CLAVE_PUBLICA,
    S_CERRAR_SESION_CLIENTE,
    S_BUSCAR_USUARIOS_POR_NOMBRE,
    S_SOLICITUDES_POR_ID,
    S_CREAR_SOLICITUD,
    S_ACEPTAR_SOLICITUD,
    S_DENEGAR_SOLICITUD,
    S_LISTA_CONTACTOS,
    S_ACTUALIZAR_CHAT,
    S_ENVIAR_MENSAJE_CHAT,
    S_CONVERSACION_CON_USUARIO,
    S_CREAR_ESPACIO,
    S_ESPACIOS_POR_ID,
    S_ELIMINAR_ESPACIO,
    S_EDITAR_ESPACIO,
    S_COMPARTIR_ESPACIO,
    S_DEJAR_DE_COMPARTIR_ESPACIO,
    S_GUARDAR_IMAGEN_PERFIL,

    // Mensajes de respuesta
    R_LOGIN_OK,
    R_TEST,
    R_CONFIRMACION,
    R_ERROR,
    R_BUSCAR_USUARIOS_POR_NOMBRE,
    R_SOLICITUDES_POR_ID,
    R_LISTA_CONTACTOS,
    R_ACTUALIZAR_CHAT,
    R_NUEVO_MENSAJE_CHAT,
    R_CONVERSACION_CON_USUARIO,
    R_CREAR_ESPACIO_OK,
    R_ESPACIOS_POR_ID,
    R_COMPARTIR_ESPACIO_OK,
    R_NUEVO_ESPACIO_RECIBIDO,
    R_ACTUALIZAR_ESPACIO_RECIBIDO,
    R_ELIMINAR_ESPACIO_RECIBIDO,
    R_ESTADO_SESION_CONTACTO,


    // Mensajes de P2P Cliente - Servidor
    S_P2P_SDP_OFERTA,
    S_P2P_SDP_RESPUESTA,
    S_P2P_ICE,

    R_P2P_SDP_OFERTA,
    R_P2P_SDP_RESPUESTA,
    R_P2P_ICE,

    // Mensajes de P2P Cliente - Cliente

    P2P_DEBUG_MENSAJE,
    P2P_S_INFO_RUTA,
    P2P_R_INFO_RUTA,
    P2P_S_DESCARGAR_FICHERO,
    P2P_R_DESCARGAR_FICHERO,
    P2P_R_FRAGMENTO_ARCHIVO,
    P2P_R_CONFIRMAR_FRAGMENTO,
    P2P_R_FIN_ARCHIVO

}