package com.p2pnexus.comun;

public enum TipoMensaje {

    NOTIFICACION,
    
    // Mensajes de consulta
    C_TEST,
    C_LOGIN,
    C_REGISTRO,
    C_SOLICITAR_CLAVE_PUBLICA,
    C_CERRAR_SESION_CLIENTE,
    C_BUSCAR_USUARIOS_POR_NOMBRE,
    C_SOLICITUDES_POR_ID,
    C_CREAR_SOLICITUD,
    C_ACEPTAR_SOLICITUD,
    C_DENEGAR_SOLICITUD,
    C_LISTA_CONTACTOS,

    // Mensajes de respuesta
    R_LOGIN_OK,
    R_TEST,
    R_CONFIRMACION,
    R_ERROR,
    R_BUSCAR_USUARIOS_POR_NOMBRE,
    R_SOLICITUDES_POR_ID,
    R_LISTA_CONTACTOS,

}
